//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIBAdminsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLogDetail
    {
        public int ChangeLogDetailsId { get; set; }
        public int FK_ChangeLogID { get; set; }
        public string Field { get; set; }
        public string PreviousValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<System.DateTime> DetailDate { get; set; }
    
        public virtual ChangeLog ChangeLog { get; set; }
    }
}
