//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIBAdminsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChangeLog()
        {
            this.ChangeLogDetails = new HashSet<ChangeLogDetail>();
        }
    
        public int ChangeLogId { get; set; }
        public int FK_SystemUserID { get; set; }
        public string Action { get; set; }
        public string Entity { get; set; }
        public int FK_RecordID { get; set; }
        public System.DateTime LogDate { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeLogDetail> ChangeLogDetails { get; set; }
    }
}
