//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APRaye7.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AP_Raye7DbEntities : DbContext
    {
        public AP_Raye7DbEntities()
            : base("name=AP_Raye7DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activities> activities { get; set; }
        public virtual DbSet<branch> branch { get; set; }
        public virtual DbSet<chat_messages> chat_messages { get; set; }
        public virtual DbSet<checkpoints> checkpoints { get; set; }
        public virtual DbSet<clusters> clusters { get; set; }
        public virtual DbSet<communities> communities { get; set; }
        public virtual DbSet<community_subscriptions> community_subscriptions { get; set; }
        public virtual DbSet<community_suggestions> community_suggestions { get; set; }
        public virtual DbSet<conversations> conversations { get; set; }
        public virtual DbSet<credits> credits { get; set; }
        public virtual DbSet<delayed_jobs> delayed_jobs { get; set; }
        public virtual DbSet<device> device { get; set; }
        public virtual DbSet<feedbacks> feedbacks { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<pickups> pickups { get; set; }
        public virtual DbSet<places> places { get; set; }
        public virtual DbSet<ratings> ratings { get; set; }
        public virtual DbSet<requested_communities> requested_communities { get; set; }
        public virtual DbSet<schedules> schedules { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<system_messages> system_messages { get; set; }
        public virtual DbSet<trip_pickup_requests> trip_pickup_requests { get; set; }
        public virtual DbSet<trips> trips { get; set; }
        public virtual DbSet<user_conversations> user_conversations { get; set; }
        public virtual DbSet<users> users { get; set; }
    
        public virtual ObjectResult<Nullable<double>> CarbonSavings(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("CarbonSavings", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> CarbonSavingsNoDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("CarbonSavingsNoDate");
        }
    
        public virtual ObjectResult<DeletedPassengerTrips_Result> DeletedPassengerTrips(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DeletedPassengerTrips_Result>("DeletedPassengerTrips", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<DeletedPassengerTripsNoDate_Result> DeletedPassengerTripsNoDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DeletedPassengerTripsNoDate_Result>("DeletedPassengerTripsNoDate");
        }
    
        public virtual ObjectResult<DeletedTripsPerBranch_Result> DeletedTripsPerBranch(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DeletedTripsPerBranch_Result>("DeletedTripsPerBranch", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<DeletedTripsPerBranchNoDate_Result> DeletedTripsPerBranchNoDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DeletedTripsPerBranchNoDate_Result>("DeletedTripsPerBranchNoDate");
        }
    
        public virtual ObjectResult<PassengerTripsPerBranch_Result> PassengerTripsPerBranch(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PassengerTripsPerBranch_Result>("PassengerTripsPerBranch", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<PassengerTripsPerBranchNoDate_Result> PassengerTripsPerBranchNoDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PassengerTripsPerBranchNoDate_Result>("PassengerTripsPerBranchNoDate");
        }
    
        public virtual ObjectResult<TopTenBranches_Result> TopTenBranches(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopTenBranches_Result>("TopTenBranches", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<TopTenBranchesNoDate_Result> TopTenBranchesNoDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopTenBranchesNoDate_Result>("TopTenBranchesNoDate");
        }
    
        public virtual ObjectResult<TotalTripsPerBranch_Result> TotalTripsPerBranch(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TotalTripsPerBranch_Result>("TotalTripsPerBranch", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<TotalTripsPerBranchNoDate_Result> TotalTripsPerBranchNoDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TotalTripsPerBranchNoDate_Result>("TotalTripsPerBranchNoDate");
        }
    
        public virtual ObjectResult<TripsPerBranch_Result> TripsPerBranch(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TripsPerBranch_Result>("TripsPerBranch", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<TripsPerBranchNoDate_Result> TripsPerBranchNoDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TripsPerBranchNoDate_Result>("TripsPerBranchNoDate");
        }
    
        public virtual ObjectResult<UsersPerBranch_Result> UsersPerBranch(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsersPerBranch_Result>("UsersPerBranch", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<UsersPerBranchNoDate_Result> UsersPerBranchNoDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsersPerBranchNoDate_Result>("UsersPerBranchNoDate");
        }
    }
}
