//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APRaye7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class communities
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> cluster_id { get; set; }
        public Nullable<int> place_id { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> type { get; set; }
        public string verifier { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
