//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APRaye7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ratings
    {
        public int id { get; set; }
        public Nullable<int> evaluator_id { get; set; }
        public Nullable<int> rated_id { get; set; }
        public Nullable<int> trip_id { get; set; }
        public Nullable<int> stars { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
