//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APRaye7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requested_communities
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string company_name { get; set; }
        public string domain { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string updated_at { get; set; }
    }
}
