//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APRaye7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_messages
    {
        public int id { get; set; }
        public string notifiable_type { get; set; }
        public Nullable<int> notifiable_id { get; set; }
        public string type { get; set; }
    }
}
