//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APRaye7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string encrypted_password { get; set; }
        public string phone_number { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<bool> have_car { get; set; }
        public Nullable<bool> smoking { get; set; }
        public Nullable<bool> same_gender { get; set; }
        public string provider { get; set; }
        public string uid { get; set; }
        public Nullable<int> rating_counter { get; set; }
        public Nullable<double> rating { get; set; }
        public string business_purpose { get; set; }
        public Nullable<int> referral_points { get; set; }
        public string referral_id { get; set; }
        public Nullable<int> referred_by_id { get; set; }
        public Nullable<int> user_points { get; set; }
        public Nullable<int> driven_points { get; set; }
        public Nullable<int> ridden_points { get; set; }
        public Nullable<int> sms_count { get; set; }
        public string tokens { get; set; }
        public Nullable<System.DateTime> last_seen { get; set; }
        public string reset_password_token { get; set; }
        public Nullable<System.DateTime> reset_password_sent_at { get; set; }
        public Nullable<System.DateTime> remember_created_at { get; set; }
        public string personal_image { get; set; }
        public Nullable<int> sign_in_count { get; set; }
        public Nullable<System.DateTime> current_sign_in_at { get; set; }
        public Nullable<System.DateTime> last_sign_in_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> default_work_place_id { get; set; }
        public Nullable<bool> soft_deleted { get; set; }
        public string image_secure_token { get; set; }
        public string time_zone { get; set; }
        public string last_sign_in_ip { get; set; }
        public string current_sign_in_ip { get; set; }
    }
}
