//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APRaye7.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashBoardV1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashBoardV1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APRaye7.App_GlobalResources.DashBoardV1", typeof(DashBoardV1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Trips.
        /// </summary>
        public static string AcceptedTrips {
            get {
                return ResourceManager.GetString("AcceptedTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Users.
        /// </summary>
        public static string ActiveUsers {
            get {
                return ResourceManager.GetString("ActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active vs. In-Active Users.
        /// </summary>
        public static string ActivevsInActivePieChart {
            get {
                return ResourceManager.GetString("ActivevsInActivePieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driven Points.
        /// </summary>
        public static string DrivenPoints {
            get {
                return ResourceManager.GetString("DrivenPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Who Have a Car.
        /// </summary>
        public static string HaveCarPercentage {
            get {
                return ResourceManager.GetString("HaveCarPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users With/Without Cars.
        /// </summary>
        public static string HaveCarPieChart {
            get {
                return ResourceManager.GetString("HaveCarPieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users With Car.
        /// </summary>
        public static string HaveCarUsers {
            get {
                return ResourceManager.GetString("HaveCarUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Active Users.
        /// </summary>
        public static string InActiveUsers {
            get {
                return ResourceManager.GetString("InActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited Trips.
        /// </summary>
        public static string InvitedTrips {
            get {
                return ResourceManager.GetString("InvitedTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male vs. Female.
        /// </summary>
        public static string MaleVsFemalePieChart {
            get {
                return ResourceManager.GetString("MaleVsFemalePieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Visited Destination.
        /// </summary>
        public static string MostVisitedDestination {
            get {
                return ResourceManager.GetString("MostVisitedDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Common Source.
        /// </summary>
        public static string MostVisitedSource {
            get {
                return ResourceManager.GetString("MostVisitedSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Users.
        /// </summary>
        public static string NumOfFemales {
            get {
                return ResourceManager.GetString("NumOfFemales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male Users.
        /// </summary>
        public static string NumOfMales {
            get {
                return ResourceManager.GetString("NumOfMales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard V1.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger Trips Made and Destroyed.
        /// </summary>
        public static string PassengerTripsPerBranchChart {
            get {
                return ResourceManager.GetString("PassengerTripsPerBranchChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointing System Score.
        /// </summary>
        public static string PointsSystem {
            get {
                return ResourceManager.GetString("PointsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrent Trips.
        /// </summary>
        public static string RecurrentTrips {
            get {
                return ResourceManager.GetString("RecurrentTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string ReportPageTitle {
            get {
                return ResourceManager.GetString("ReportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Trips.
        /// </summary>
        public static string RequestedTrips {
            get {
                return ResourceManager.GetString("RequestedTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ridden Points.
        /// </summary>
        public static string RiddenPoints {
            get {
                return ResourceManager.GetString("RiddenPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users With Same Gender.
        /// </summary>
        public static string SameGenderUsers {
            get {
                return ResourceManager.GetString("SameGenderUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smokers Percentage.
        /// </summary>
        public static string SmokersPercentage {
            get {
                return ResourceManager.GetString("SmokersPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Who Smoke.
        /// </summary>
        public static string SmokeUsers {
            get {
                return ResourceManager.GetString("SmokeUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Trips Today.
        /// </summary>
        public static string TodayTrips {
            get {
                return ResourceManager.GetString("TodayTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Ten Visited Branches.
        /// </summary>
        public static string TopTenChart {
            get {
                return ResourceManager.GetString("TopTenChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Ten Users.
        /// </summary>
        public static string TopTenUsers {
            get {
                return ResourceManager.GetString("TopTenUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Cancelled Trips.
        /// </summary>
        public static string TotalCancelledTrips {
            get {
                return ResourceManager.GetString("TotalCancelledTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Posted Trips.
        /// </summary>
        public static string TotalPostedTrips {
            get {
                return ResourceManager.GetString("TotalPostedTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Trips.
        /// </summary>
        public static string TotalTrips {
            get {
                return ResourceManager.GetString("TotalTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Trips Per Branch.
        /// </summary>
        public static string TotalTripsPerBranchChart {
            get {
                return ResourceManager.GetString("TotalTripsPerBranchChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Trips Made and Destroyed.
        /// </summary>
        public static string TripsPerBranch {
            get {
                return ResourceManager.GetString("TripsPerBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Trips Made and Destroyed.
        /// </summary>
        public static string TripsPerBranchChart {
            get {
                return ResourceManager.GetString("TripsPerBranchChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trips Per Building.
        /// </summary>
        public static string TripsPerBuilding {
            get {
                return ResourceManager.GetString("TripsPerBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trips vs. Recurrent Trips.
        /// </summary>
        public static string TripsvsRecurrentTripsPieChart {
            get {
                return ResourceManager.GetString("TripsvsRecurrentTripsPieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Points.
        /// </summary>
        public static string UserPoints {
            get {
                return ResourceManager.GetString("UserPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Users.
        /// </summary>
        public static string UsersCount {
            get {
                return ResourceManager.GetString("UsersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Per Branch.
        /// </summary>
        public static string UsersPerBranchChart {
            get {
                return ResourceManager.GetString("UsersPerBranchChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Statistics.
        /// </summary>
        public static string UserStatisticsBarChart {
            get {
                return ResourceManager.GetString("UserStatisticsBarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of users till today.
        /// </summary>
        public static string UsersTillToday {
            get {
                return ResourceManager.GetString("UsersTillToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Without Car.
        /// </summary>
        public static string UsersWithoutCars {
            get {
                return ResourceManager.GetString("UsersWithoutCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users With Car.
        /// </summary>
        public static string UserWithCars {
            get {
                return ResourceManager.GetString("UserWithCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User With Most Trips.
        /// </summary>
        public static string UserWithMostTrips {
            get {
                return ResourceManager.GetString("UserWithMostTrips", resourceCulture);
            }
        }
    }
}
