//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APRaye7.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SessionVariables_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SessionVariables_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APRaye7.App_GlobalResources.SessionVariables_Resource", typeof(SessionVariables_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveTab.
        /// </summary>
        public static string ActiveTab {
            get {
                return ResourceManager.GetString("ActiveTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BreadCrumbLinks.
        /// </summary>
        public static string BreadCrumbLinks {
            get {
                return ResourceManager.GetString("BreadCrumbLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BreadCrumbText.
        /// </summary>
        public static string BreadCrumbText {
            get {
                return ResourceManager.GetString("BreadCrumbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletedWithErrors.
        /// </summary>
        public static string CompletedWithErrors {
            get {
                return ResourceManager.GetString("CompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastPage.
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string Menus {
            get {
                return ResourceManager.GetString("Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiLingual.
        /// </summary>
        public static string MultiLingual {
            get {
                return ResourceManager.GetString("MultiLingual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfLoginTrials.
        /// </summary>
        public static string NumberOfLoginTrials {
            get {
                return ResourceManager.GetString("NumberOfLoginTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageStatus.
        /// </summary>
        public static string PageStatus {
            get {
                return ResourceManager.GetString("PageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentMenu.
        /// </summary>
        public static string ParentMenu {
            get {
                return ResourceManager.GetString("ParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        public static string Parents {
            get {
                return ResourceManager.GetString("Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreventLogIn.
        /// </summary>
        public static string PreventLogIn {
            get {
                return ResourceManager.GetString("PreventLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedMenu.
        /// </summary>
        public static string SelectedMenu {
            get {
                return ResourceManager.GetString("SelectedMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
