//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APRaye7.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Users_resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Users_resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APRaye7.App_GlobalResources.Users_resource", typeof(Users_resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Birth_Date {
            get {
                return ResourceManager.GetString("Birth_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Purprose.
        /// </summary>
        public static string Business_Purpose {
            get {
                return ResourceManager.GetString("Business_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Driver Trips.
        /// </summary>
        public static string CancelledDriverTrips {
            get {
                return ResourceManager.GetString("CancelledDriverTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Passenger Trips.
        /// </summary>
        public static string CancelledPassengerTrips {
            get {
                return ResourceManager.GetString("CancelledPassengerTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string Created_At {
            get {
                return ResourceManager.GetString("Created_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Sign In At.
        /// </summary>
        public static string Current_Sign_In_At {
            get {
                return ResourceManager.GetString("Current_Sign_In_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driven Points.
        /// </summary>
        public static string Driven_Points {
            get {
                return ResourceManager.GetString("Driven_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Trips.
        /// </summary>
        public static string DriverTrips {
            get {
                return ResourceManager.GetString("DriverTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a Car.
        /// </summary>
        public static string Have_Car {
            get {
                return ResourceManager.GetString("Have_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Seen.
        /// </summary>
        public static string Last_Seen {
            get {
                return ResourceManager.GetString("Last_Seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Rides Driven by User.
        /// </summary>
        public static string NumberOfRides {
            get {
                return ResourceManager.GetString("NumberOfRides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger Trips.
        /// </summary>
        public static string PassengerTrips {
            get {
                return ResourceManager.GetString("PassengerTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Image.
        /// </summary>
        public static string Personal_Image {
            get {
                return ResourceManager.GetString("Personal_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Counter.
        /// </summary>
        public static string Rating_Counter {
            get {
                return ResourceManager.GetString("Rating_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Points.
        /// </summary>
        public static string Referral_Points {
            get {
                return ResourceManager.GetString("Referral_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ridden Points.
        /// </summary>
        public static string Ridden_Points {
            get {
                return ResourceManager.GetString("Ridden_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Gender.
        /// </summary>
        public static string Same_Gender {
            get {
                return ResourceManager.GetString("Same_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In Count.
        /// </summary>
        public static string Sign_In_Count {
            get {
                return ResourceManager.GetString("Sign_In_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking.
        /// </summary>
        public static string Smoking {
            get {
                return ResourceManager.GetString("Smoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Count.
        /// </summary>
        public static string SMS_Count {
            get {
                return ResourceManager.GetString("SMS_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens.
        /// </summary>
        public static string Tokens {
            get {
                return ResourceManager.GetString("Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modification Date.
        /// </summary>
        public static string Updated_At {
            get {
                return ResourceManager.GetString("Updated_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Points.
        /// </summary>
        public static string User_Points {
            get {
                return ResourceManager.GetString("User_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string UserPointsDetailed {
            get {
                return ResourceManager.GetString("UserPointsDetailed", resourceCulture);
            }
        }
    }
}
